name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.58.3'
    - name: Build
      run: hugo --minify
    - name: Commit files
      run: |
        cd public
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "deploy public" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
